---
language: ruby
sudo: false
cache: bundler
env: CODECLIMATE_REPO_TOKEN=f5b27b2e25d3f4e199bb2566fb4fd4507144a004c71d4aa33a32c2df5f940333
rvm: "1.9.3"
before_install: rvm get stable

matrix:
  include:
  - rvm: "1.9.3"
    gemfile: gemfiles/rails_3.2.gemfile
